# Discard Chache Older Than X
max_cache_age = "2d"

# Max retries before link is labeled dead
max_retries = 2

# Max concurrent link checkers
max_concurrency = 14

# Acceptable
# 200: Valid link, 403: Forbidden URL, 429: Too Many Requests
accept = ["200", "403", "429"]
