exclude = [
	"*.png"
	"https://bcrw.apple.com/*",
	"https://www.messenger.com/t/1224106861035505?text=resist",
	"https://www.instagram.com/direct/t/107534807309194/?text=",
	"https://t.me/resistbot?start=resist",
	"https://online.osu.edu/*"
	"https://www.powells.com/*"
]
