name: Link Checker

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # checks once a day

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
