name: Spell Check

on:
  push:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell checker
        uses: codespell-project/actions-codespell@v2
